dispatcher:
    bind: [ "udp4://127.0.0.1:53","tcp4://127.0.0.1:53","udp6://[::1]:53","tcp6://[::1]:53" ]
    max_udp_size: 1280
upstream:
    local:
        server: "aliyun"
        policies:
            query:
                unhandlable_types: "accept"
                domain: "accept:./chn_domain.list|deny:./non_chn_domain.list"
            reply:
                error_rcode: "deny"
                cname: "accept:./chn_domain.list"
                without_ip: "deny"
                ip: "accept:./chn_ip.list|deny"
    remote:
        server: "google"
        policies:
            query:
                unhandlable_types: "accept"
                domain: "deny:./chn_domain.list|accept"
            reply:
                error_rcode: ""
                cname: ""
                without_ip: ""
                ip: ""
server:
    aliyun:
        addr: "223.5.5.5:443"
        protocol: "doh"
        socks5: ""
        tcp:
            idle_timeout: 5
        dot:
            server_name: "dns.alidns.com"
            idle_timeout: 5
        doh:
            url: "https://223.5.5.5/dns-query"
        deduplicate: false
        edns0:
            client_subnet:
                ipv4: ""
                ipv6: ""
            overwrite_ecs: false
    google:
        addr: "8.8.8.8:443"
        protocol: "doh"
        socks5: ""
        tcp:
            idle_timeout: 5
        dot:
            server_name: "dns.google"
            idle_timeout: 5
        doh:
            url: "https://dns.google/dns-query"
        deduplicate: false
        edns0:
            client_subnet:
                ipv4: ""
                ipv6: ""
            overwrite_ecs: false
ipset:
    check_cname: false
    mask4: 0
    mask6: 0
    rule:
        - set_name4: ""
          set_name6: ""
          domain: ""
        - set_name4: ""
          set_name6: ""
          domain: ""
ca:
    path: []
